# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('landmark', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('pin', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
