# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20181217_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=64)),
                ('property_for', models.CharField(max_length=64)),
                ('property_type', models.CharField(max_length=64)),
                ('property_bedrooms', models.PositiveIntegerField()),
                ('property_balconies', models.PositiveIntegerField()),
                ('property_flor_number', models.CharField(max_length=64)),
                ('property_covered_area', models.PositiveIntegerField()),
                ('property_carpet_area', models.PositiveIntegerField()),
                ('property_price', models.PositiveIntegerField()),
            ],
        ),
    ]
