# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
