# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-18 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_property_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_name',
        ),
    ]
