# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-18 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_remove_property_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='society_name',
            new_name='wing_name',
        ),
    ]
