# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20181218_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_contact',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_owner',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
