# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-18 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20181218_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_person', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('contact', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='householdservices',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='basic_app.HouseholdTypes'),
        ),
    ]
