# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-19 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20181218_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_picture',
            field=models.ImageField(),
            preserve_default=False,
        ),
    ]
