# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_property_property_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_picture',
            field=models.ImageField(),
        ),
    ]
