# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-19 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_auto_20181219_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_month', models.CharField(max_length=64)),
                ('maintenance_amount', models.PositiveIntegerField()),
                ('maintenance_payment_mode', models.CharField(max_length=64)),
            ],
        ),
    ]
