# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
