# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-25 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_auto_20181221_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_picture',
            field=models.FileField(upload_to='media'),
        ),
    ]
