# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-25 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_complaintpost_noticepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event_type', models.CharField(max_length=64)),
                ('event_description', models.TextField(max_length=500)),
            ],
        ),
    ]
