# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(),
        ),
    ]
