# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_auto_20181225_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default=['%d-%m-%y']),
        ),
    ]
