# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-26 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_auto_20181226_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='flat_no',
        ),
        migrations.RemoveField(
            model_name='society',
            name='wing_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='flat_no',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='wing_name',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
    ]
