# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0022_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Society',
        ),
        migrations.AddField(
            model_name='profile',
            name='society_address',
            field=models.TextField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='society_name',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
    ]
