# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-27 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0024_auto_20181227_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
    ]
