# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-30 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0026_noticepost_notice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticepost',
            name='notice_file',
            field=models.FileField(blank=True, upload_to='pics'),
        ),
    ]
