# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-30 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0028_auto_20181230_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticepost',
            name='notice_by',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
    ]
