# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-09 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0032_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintpost',
            name='complaint_by',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintpost',
            name='complaint_status',
            field=models.CharField(default='Initiate', max_length=64),
        ),
    ]
