# Generated by Django 2.1.5 on 2019-01-17 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0035_auto_20190110_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdservices',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='basic_app.HouseholdTypes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
