# Generated by Django 2.1.5 on 2019-02-05 08:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0037_auto_20190205_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintpost',
            name='user',
            field=models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
