# Generated by Django 2.1.5 on 2019-02-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0039_auto_20190205_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintpost',
            name='user',
        ),
    ]
