# Generated by Django 2.1.5 on 2019-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0040_remove_complaintpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='registered_by',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
    ]
