# Generated by Django 2.1.5 on 2019-02-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0042_auto_20190206_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='userna',
        ),
    ]
