# Generated by Django 2.1.5 on 2019-02-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0043_auto_20190206_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userna',
            new_name='user',
        ),
    ]
