# Generated by Django 2.1.5 on 2019-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0044_auto_20190206_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
