# Generated by Django 2.1.5 on 2019-02-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0045_auto_20190207_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
