# Generated by Django 2.1.5 on 2019-02-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0046_auto_20190207_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
    ]
