# Generated by Django 2.1.5 on 2019-02-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0047_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='username_again',
        ),
    ]
