# Generated by Django 2.1.5 on 2019-02-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0048_auto_20190207_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='date',
            field=models.DateField(default='yyyy-mm-dd'),
        ),
    ]
