# Generated by Django 2.1.5 on 2019-02-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0049_auto_20190208_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='booked_by',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
    ]
