# Generated by Django 2.1.5 on 2019-02-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0050_hall_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default=11, max_length=512),
            preserve_default=False,
        ),
    ]
