# Generated by Django 2.1.5 on 2019-02-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0051_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.CharField(choices=[(1, 'Sell'), (2, 'Rent')], default=1, max_length=64),
        ),
    ]
