# Generated by Django 2.1.5 on 2019-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0052_auto_20190211_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.IntegerField(choices=[(1, 'Sell'), (2, 'Rent')], default=1, max_length=64),
        ),
    ]
