# Generated by Django 2.1.5 on 2019-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0053_auto_20190211_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.IntegerField(choices=[(1, 'Sell'), (2, 'Rent')], default=1),
        ),
    ]
