# Generated by Django 2.1.5 on 2019-02-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0054_auto_20190211_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], default=1, max_length=64),
        ),
    ]
