# Generated by Django 2.1.5 on 2019-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0055_auto_20190211_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_bedrooms',
        ),
        migrations.AddField(
            model_name='property',
            name='property_BHK',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_balconies',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_for',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent'), ('PG', 'PG')], default=1, max_length=64),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Tenament', 'Tenament'), ('Duplex', 'Duplex'), ('Penthouse', 'Penthouse')], max_length=64),
        ),
    ]
