# Generated by Django 2.1.5 on 2019-02-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0057_auto_20190211_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_flor_number',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=64),
        ),
    ]
