# Generated by Django 2.1.5 on 2019-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0059_auto_20190211_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticepost',
            name='notice_subject',
            field=models.CharField(max_length=5),
        ),
    ]
