# Generated by Django 2.1.5 on 2019-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0060_auto_20190211_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintpost',
            name='complaint_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaintpost',
            name='complaint_subject',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hall',
            name='event_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hall',
            name='event_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='householdservices',
            name='contact',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='householdservices',
            name='service_person',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='notice_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='notice_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='notice_subject',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='bhk',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_contact',
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_owner',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_picture',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='wing_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
