# Generated by Django 2.1.5 on 2019-02-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0061_auto_20190211_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='mode',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default=11, max_length=10),
            preserve_default=False,
        ),
    ]
