# Generated by Django 2.1.5 on 2019-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0062_property_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_prefix', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=10)),
                ('visitor_name', models.CharField(max_length=20)),
                ('host_name', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField(auto_now=True)),
                ('time_out', models.DateTimeField()),
            ],
        ),
    ]
