# Generated by Django 2.1.5 on 2019-02-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0063_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='time_out',
            field=models.TimeField(),
        ),
    ]
