# Generated by Django 2.1.5 on 2019-02-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0064_auto_20190212_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
