# Generated by Django 2.1.5 on 2019-02-12 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0065_auto_20190212_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintpost',
            name='complaint_subject',
        ),
        migrations.AddField(
            model_name='complaintpost',
            name='category',
            field=models.CharField(choices=[('housekeeping', 'housekeeping'), ('Security', 'Security'), ('Service', 'service'), ('Suggestions/Feedback', 'Suggestions/Feedback')], default=111, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintpost',
            name='subcategory',
            field=models.CharField(choices=[('Children Play Area', 'Children Play Area'), ('Common Area', 'Common Area'), ('Electric/Wiring', 'Electric/Wiring'), ('Exterior/Cabling', 'Exterior/Cabling'), ('Exterior/Wall/Paint', 'Exterior/Wall/Paint'), ('Generator', 'Generator'), ('Gym', 'Gym'), ('Interior/Walls/Paint', 'Interior/Walls/Paint'), ('Interior/Wood Work', 'Interior/Wood Work'), ('Lifts', 'Lifts'), ('Others', 'Others'), ('Plumbing', 'Plumbing'), ('Sewage', 'Sewage')], default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_out',
            field=models.TimeField(blank=True, default='00:00:00py'),
        ),
    ]
