# Generated by Django 2.1.5 on 2019-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0066_auto_20190212_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flat', models.CharField(max_length=10)),
                ('designation', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Treasurer', 'Treasurer'), ('Executive Member', 'Executive Member')], max_length=30)),
                ('contact', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=30)),
                ('days', models.CharField(max_length=30)),
                ('timing', models.TimeField()),
                ('contact', models.PositiveIntegerField()),
            ],
        ),
    ]
