# Generated by Django 2.1.5 on 2019-02-13 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0068_auto_20190213_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 11, 19, 10, 883297, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='votedone',
            name='vote_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
