# Generated by Django 2.1.5 on 2019-02-13 11:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0069_auto_20190213_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='votedone',
            name='byy',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL), max_length=30),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 11, 23, 50, 311713, tzinfo=utc)),
        ),
    ]
