# Generated by Django 2.1.5 on 2019-03-08 06:04

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0078_auto_20190216_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='time_out',
        ),
        migrations.AddField(
            model_name='complaintpost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 6, 4, 51, 399933, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hall',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 8, 6, 4, 51, 399933, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='noticepost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 6, 4, 51, 399933, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='visitor',
            name='date_and_time_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 8, 6, 4, 51, 399933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 6, 4, 51, 420399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentadd',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 6, 4, 51, 421400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='committee',
            name='contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter 10 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='hall',
            name='event_type',
            field=models.CharField(choices=[('Reception', 'Reception'), ('Buffets', 'Buffets'), ('Lunch/Dinner Meeting', 'Lunch/Dinner Meeting'), ('Conference', 'Conference'), ('Special Events', 'Special Events'), ('Traditional Events', 'Traditional Events'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='householdservices',
            name='contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter 10 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='householdservices',
            name='service_person',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='householdtypes',
            name='services',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='notice_subject',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flat_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house_name',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='society_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wing_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter 10 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_owner',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='wing_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 6, 4, 51, 399933, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter 10 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='service',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 6, 4, 51, 399933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='host_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic_app.Profile'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Only alphabets are allowed.')]),
        ),
    ]
