# Generated by Django 2.1.5 on 2019-03-08 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0080_auto_20190308_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vehicles',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 12, 5, 9, 853288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='commentadd',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 12, 5, 9, 857288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaintpost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 12, 5, 9, 837289, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hall',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 8, 12, 5, 9, 837289, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 12, 5, 9, 837289, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='notice_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 12, 5, 9, 841288, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 12, 5, 9, 841288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_and_time_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 8, 12, 5, 9, 841288, tzinfo=utc)),
        ),
    ]
